ALTER TABLE users 
ADD COLUMN IF NOT EXISTS location GEOGRAPHY(Point, 4326),
ADD COLUMN IF NOT EXISTS heading FLOAT DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS is_dnd BOOLEAN DEFAULT false;

CREATE INDEX IF NOT EXISTS users_location_idx ON users USING GIST (location);